### ISSUE TITLE
ExDoc warning

### ISSUE THREAD

**Issue by lleger** [puid/Elixir#8]
When generating docs in an app with a module that has `use Puid`, you get the following warning when running `mix docs`:

```
warning: documentation references module "Puid.Info" but it is hidden
  lib/my_app/schema.ex:1: MyApp.Schema.info/0
```

Version info:
Elixir v1.11
ExDoc v0.24.2
OTP 23

**Comment by dingosky** [comment]
Thanks Logan. I *think* I fix the issue by adding a module doc string to
the Puid.Info module (which was previously marked as @moduledoc false).
However, I was unable to reproduce your issue myself, so this is a bit of a
guess (though I believe somewhat informed).

The proposed fix is in Puid version 1.1.2

Do let me know if you still see the issue and I’ll dive deeper.

Regards,

Paul

On September 14, 2021 at 11:04:14, Logan Leger ***@***.***)
wrote:

When generating docs in an app with a module that has use Puid, you get the
following warning when running mix docs:

warning: documentation references module "Puid.Info" but it is hidden
  lib/my_app/schema.ex:1: MyApp.Schema.info/0

Version info:
Elixir v1.11
ExDoc v0.24.2
OTP 23

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/puid/Elixir/issues/8>, or unsubscribe

**Comment by lleger** [comment]
@dingosky That worked! No more error and it's now linked in the generated docs. (Although the link is broken, not sure why: https://hexdocs.pm/puid/1.1.2/Puid.Info.html)

**Comment by dingosky** [comment]
bc I had failed to publish the docs for 1.1.2 😖   Done now....
